version: "3"
services:
  
  worker_1:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-analysis:latest
    hostname: worker_1
    volumes:
      - .:/Analysis
  worker_2:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-analysis:latest
    hostname: worker_2
    volumes:
      - .:/Analysis
  worker_3:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-analysis:latest
    hostname: worker_3
    volumes:
      - .:/Analysis
