version: "3"
services:
  
  worker_1:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-analysis:latest
    hostname: worker_1
    command: -A workerA worker 
    volumes:
      - .:/Analysis
  worker_2:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-analysis:latest
    hostname: worker_1
    command: -A workerB worker
    volumes:
      - .:/Analysis
  worker_3:
    build:
      context: .
      dockerfile: Dockerfile
    image: github-analysis:latest
    hostname: worker_1
    command: -A workerC worker
    volumes:
      - .:/Analysis
